apiVersion: v1
kind: Service
metadata:
  name: blockmart-frontend-svc
spec:
  type: NodePort # Allows external access to your local cluster
  selector:
    app: blockmart-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
      nodePort: 30080